extends: split_taxonomy_age.yaml

training:
  gradient_strategy: {type: pcgrad}

sweep:
  parameters:
    seed: [42]

wandb:
  group: generalisation-split-pcgrad
  tags: [generalisation, split-taxonomy-age, pcgrad]

slurm:
  planning:
    run_name_prefix: split_pcgrad
